[package]
authors = ["Bilal Elmoussaoui <bil.elmoussaoui@gmail.com>"]
categories = ["gui", "os::linux-apis", "api-bindings"]
description = "XDG portals wrapper in Rust using zbus"
edition = "2018"
exclude = ["interfaces/*.xml"]
keywords = ["portal", "flatpak", "xdg", "desktop", "documents"]
license = "MIT"
name = "ashpd"
repository = "https://github.com/bilelmoussaoui/ashpd"
version = "0.1.0"

[features]
feature_gtk = ["gdk", "gdkx11", "gtk"]

[dependencies]
enumflags2 = "0.6"
serde = {version = "1.0", features = ["derive"]}
serde_repr = "0.1"
strum = "0.19"
strum_macros = "0.19"
zbus = {version = "1.1"}
zvariant = {version = "2.2", features = ["enumflags2"]}
zvariant_derive = {version = "2.2"}

[dependencies.gdk]
package = "gdk4"
optional = true
git = "https://github.com/gtk-rs/gtk4-rs.git"

[dependencies.gtk]
package = "gtk4"
optional = true
git = "https://github.com/gtk-rs/gtk4-rs.git"

[dependencies.gdkx11]
package = "gdk4-x11"
optional = true
git = "https://github.com/gtk-rs/gtk4-rs.git"
